ALTER TABLE test.ORDER
    DROP CONSTRAINT fk_older_delivery_company;

ALTER TABLE test.ORDER
    DROP CONSTRAINT fk_order_paymnets;

ALTER TABLE test.ORDER
    DROP CONSTRAINT fk_order_user;

ALTER TABLE test.CATEGORY_LIST
    DROP CONSTRAINT fk_category_in_list_category;

ALTER TABLE test.GOODS_DESCRIPTION
    DROP CONSTRAINT fk_fabricator_goods;

ALTER TABLE test.GOODS
    DROP CONSTRAINT fk_goods_description;

ALTER TABLE test.ORDER_GOODS
    DROP CONSTRAINT fk_goods_in_order;

ALTER TABLE test.ORDER_GOODS
    DROP CONSTRAINT  fk_goods_in_order_goods;

ALTER TABLE test.CATEGORY_LIST
    DROP CONSTRAINT fk_list_category;

/*******************  DROPS  TABLES  *******************/

DROP TABLE test.DELIVERY_COMPANY;

DROP TABLE test.ORDER;

DROP TABLE test.ORDER_GOODS;

DROP TABLE test.PAYMENTS;

DROP TABLE test.USER;

DROP TABLE test.CATEGORY;

DROP TABLE test.CATEGORY_LIST;

DROP TABLE test.FABRICATOR;

DROP TABLE test.GOODS;

DROP TABLE test.GOODS_DESCRIPTION;
